Setup webpack in dev dependancies
dj-fiorex/angular2-smart-table pull request #64
Opened 2022-05-15 12:10 UTC by tawfiek

# The Problem

When I was trying to setup me development environment I faced an issue that related to the webpack module is not found, and took me a while to figure out what should I do with this package to start to dive into the code.

# Solution
I added the webpack to the development dependancies and added some basic instruction for the new comers in order to save some time understanding how to start with developing in this project

2022-05-23 12:35 UTC, uap-universe commented
webpack is a peer dependency of the Angular Devkit and _should not_ be mentioned explicitly.

Please try the following (first, without explicit webpack dependency):
1. Delete the `node_modules` folder
2. Delete the `package-lock.json`
3. Run `npm i`

Also make sure you have the recent npm installed (your npm produces lockfile version 1, which indicates you are still using npm 6 or npm 5).

If it really does not work - for some awkward reason - you can add the webpack dependency explicitly, but it would be great if you could produce a lockfile with lockfileVersion: 2.

The combined build script is very much welcome though and can stay in this PR - I approve as soon as the above things are addressed.

2022-05-23 12:38 UTC, uap-universe requested changes
webpack is a peer dependency of the Angular Devkit and should not be mentioned explicitly.

Please try the following (first, without explicit webpack dependency):

1.    Delete the node_modules folder
2.  Delete the package-lock.json
3.  Run `npm i`

Also make sure you have the recent npm installed (your npm produces lockfile version 1, which indicates you are still using npm 6 or npm 5).

If it really does not work - for some awkward reason - you can add the webpack dependency explicitly, but it would be great if you could produce a lockfile with lockfileVersion: 2.

The combined build script is very much welcome though and can stay in this PR - I approve as soon as the above things are addressed.

2022-06-20 20:34 UTC, tawfiek commented
@uap-universe 
Thank you for clarification, I built using node 16 and npm 8, and everything looks great.
I think we should add this information somewhere .

2022-06-21 07:05 UTC, uap-universe approved these changes

2022-06-21 07:08 UTC, merged